export const GET_ALL_BUDGET = 'GET_ALL_BUDGET';
export const ADD_NEW_REVISION_VOLUME_PRESTATION = 'ADD_NEW_REVISION_VOLUME_PRESTATION';
export const EDIT_REVISION_VOLUME_PRESTATION = 'EDIT_REVISION_VOLUME_PRESTATION';
export const VALIDATE_REVISION_VOLUME_PRESTATION = 'VALIDATE_REVISION_VOLUME_PRESTATION';
export const GET_REVISION_VOLUME_PRESTATION_BY_CODE = 'GET_REVISION_VOLUME_PRESTATION_BY_CODE';