export const GET_ALL_BUDGET_FILTRER = "GET_ALL_BUDGET_FILTRER";
export const GET_ALL_BUDGET = 'GET_ALL_BUDGET';
export const SET_SELECTED_REVISION_VOLUME_SANS_ACTE = 'SET_SELECTED_REVISION_VOLUME_SANS_ACTE';
export const ADD_NEW_REVISION_VOLUME_SANS_ACTE = 'ADD_NEW_REVISION_VOLUME_SANS_ACTE';
export const EDIT_REVISION_VOLUME_SANS_ACTE = 'EDIT_REVISION_VOLUME_SANS_ACTE';
export const VALIDATE_REVISION_VOLUME_SANS_ACTE = 'VALIDATE_REVISION_VOLUME_SANS_ACTE';
export const GET_REVISION_VOLUME_SANS_ACTE_BY_CODE = 'GET_REVISION_VOLUME_SANS_ACTE_BY_CODE';
export const SET_SELECTIONS_SANS_ACTE = 'SET_SELECTIONS_SANS_ACTE';