export const GET_ALL_BUDGET_FILTRER = "GET_ALL_BUDGET_FILTRER";
export const SHOW_ASIDE_ADD_MODE_CA_SOCIETE = "SHOW_ASIDE_ADD_MODE_CA_SOCIETE";
export const SHOW_ASIDE_CONSULT_MODE_CA_SOCIETE = "SHOW_ASIDE_CONSULT_MODE_CA_SOCIETE";
export const SHOW_ASIDE_EDIT_MODE_CA_SOCIETE = "SHOW_ASIDE_EDIT_MODE_CA_SOCIETE";
export const SHOW_ASIDE_VALIDATE_MODE_CA_SOCIETE = "SHOW_ASIDE_VALIDATE_MODE_CA_SOCIETE";
export const CLOSE_ASIDE_CA_SOCIETE = "CLOSE_ASIDE_CA_SOCIETE";
export const RESET_ASIDE_CA_SOCIETE = "RESET_ASIDE_CA_SOCIETE";
export const GET_ALL_CATAEGORIE_SOCIETE = "GET_ALL_CATAEGORIE_SOCIETE";
export const GET_ALL_SOCIETE_BY_BUDGET = "GET_ALL_SOCIETE_BY_BUDGET";
export const GET_COMPTEUR_CA_SOCIETE = "GET_COMPTEUR_CA_SOCIETE";
export const GET_HISTORIQUE_CA_BY_SOCIETE="GET_HISTORIQUE_CA_BY_SOCIETE";
export const GET_SOMME_POUR_VARIATION="GET_SOMME_POUR_VARIATION";
export const SHOW_MODAL_CONFIRMATION_CA_SOCIETE="SHOW_MODAL_CONFIRMATION_CA_SOCIETE";
export const CLOSE_MODAL_CONFIRMATION_CA_SOCIETE="CLOSE_MODAL_CONFIRMATION_CA_SOCIETE";
export const SHOW_MODAL_CHART_CA_SOCIETE="SHOW_MODAL_CHART_CA_SOCIETE";
export const CLOSE_MODAL_CHART_CA_SOCIETE="CLOSE_MODAL_CHART_CA_SOCIETE";


