export const GET_ALL_BUDGET = 'GET_ALL_BUDGET';
export const GET_ALL_REVISION_CA_SOCIETES = 'GET_ALL_REVISION_CA_SOCIETES';
export const ADD_NEW_REVISION_CA_SOCIETE = 'ADD_NEW_REVISION_CA_SOCIETE';
export const EDIT_REVISION_CA_SOCIETE = 'EDIT_REVISION_CA_SOCIETE';
export const VALIDATE_REVISION_CA_SOCIETE = 'VALIDATE_REVISION_CA_SOCIETE';
export const GET_REVISION_CA_SOCIETE_BY_CODE = 'GET_REVISION_CA_SOCIETE_BY_CODE';